### ISSUE TITLE
Comparison with pluvial/svelte-adapter-deno

### ISSUE THREAD

**Issue by Malix-Labs** [dbushell/sveltekit-adapter-deno#17]
I'm curious, what motivated you (@dbushell) to build this adapter when https://github.com/pluvial/svelte-adapter-deno existed since [3 years](https://github.com/pluvial/svelte-adapter-deno/commit/77023756b0bc4f30e06f0f31104d5a5691fac7bf) ?
Was it broken?
Why not contributing with a fork instead ?

**Comment by dbushell** [comment]
Partly discussed here:
https://github.com/pluvial/svelte-adapter-deno/issues/40

Basically **Deno Deploy** has (or had) major limitations like dynamic imports. The other adapter used the **Rollup** bundler which generated incompatible build for Deno Deploy.

My adapter started as an experimental test using **esbuild**.

I would have preferred to contribute to the existing adapter but since it's such a major refactor it would have required a PR changing like 90% of the code.

**Comment by Malix-Labs** [comment]
Understandable, thanks for this clarification !

It would be nice to have this explanation and rationale in the README

Do you know which is more future-proof ?

I thought Vite was moving to Rolldown aka rollup-rewritten-in-rust

**Comment by dbushell** [comment]
I don't know about Vite. The official [Node adapter](https://github.com/sveltejs/kit/tree/main/packages/adapter-node) still uses Rollup which is why `pluvial/svelte-adapter-deno` uses it.

I'm not sure either adapter is future proof! Unless SvelteKit has major breaking changes they should both continue to work.

There are open issues for native SvelteKit support in Deno. I would expect in the future you won't need a special Deno adapter once Deno can handle the Node APIs.

**Comment by Malix-Labs** [comment]
> I would expect in the future you won't need a special Deno adapter once Deno can handle the Node APIs

That may be more of a node compatibility layer rather than a native deno advantageous redesign

**Comment by Malix-Labs** [comment]
_btw, i need help making https://github.com/sveltejs/cli/issues/214#issuecomment-2433745245 work with deno 2 + sveltekit 5 ; can you help by chance ?_
