### ISSUE TITLE
Build process gets stuck on "using deno-deploy-adapter"

### ISSUE THREAD

**Issue by HighPriest** [dbushell/sveltekit-adapter-deno#18]
When running `deno task build`, when everything seems to be completed & vite shows "Run npm run preview to preview your production build locally", an unexpected  
```bash
> Using deno-deploy-adapter
    done
```
appears, takes over the terminal & starts listening on port 9090, apparently not doing anything. Only CTRL+C helps.

I suspect, this is also a reason for my custom "postbuild" scripts (from package.json) not getting triggered.

**Comment by dbushell** [comment]
You would have to run in the build directory:

```
deno run --allow-env --allow-read --allow-net mod.ts
```

This will launch the Deno server using the adapter.

I'm not sure how `npm run preview` works but that is still using Node and Vite.

**Comment by dbushell** [comment]
I've tested on the latest SvelteKit demo project — `npx sv create` — and the `npm run preview` works fine.

Port `9090` is not the standard Vite preview port (4173) and SvelteKit has no default `postbuild` script, so the issue is with your project somewhere I suspect. It must be assuming a Node adapter build or something.

**Comment by HighPriest** [comment]
The _postbuild_ comment is just to indicate that the build process doesn't actually finish, because the default build script tries to run some `deno-deploy`adapter at the end.

I don't want anything related to deno deploy. I just want the server to be compiled.

This happens on a clean project, created with:
- `deno run -A npm: sv create`
- `deno install`
- `deno add -D npm:sveltekit-adapter-deno`

& with default config
```
const config = { kit: { adapter: adapter(), }, };
```

**Comment by dbushell** [comment]
There is nothing specific to Deno Deploy in this adapter, it's just compatible with that hosting.

After `npm run build` It is correct to see:

```
> Using deno-deploy-adapter
  ✔ done
```

"deno-deploy-adapter" is just the name of this adapter because "deno-adapter" already exists.

The build server is in the `/build` directory and the Deno entry point is `build/mod.ts` 

I set up a new SvelteKit project in [/demo](https://github.com/dbushell/sveltekit-adapter-deno/tree/main/demo) today to confirm it still works.

Are you sure you've configured [svelte.config.js](https://github.com/dbushell/sveltekit-adapter-deno/blob/main/demo/svelte.config.js) to import the correct adapter?

```js
import adapter from "sveltekit-adapter-deno";
```

I'm not sure what issue you're facing, does the terminal get stuck after the build?

**Comment by HighPriest** [comment]
Yes sir!  
The job doesn't terminate, terminal gets stuck. Trying to CTRL+C frees control over the input, but uninteractable text "Do you want to close the batch job (Y/N)" appears from time to time, glitching out the terminal window.

**Comment by dbushell** [comment]
I have no idea, sorry! I can't reproduce the issue.

Are you trying to run SvelteKit and Vite using Deno, or Node?

So basically this adapter is designed for SvelteKit dev running under Node. The build is done by Node and only the output in `/build` is run in Deno for the final server.

If you're trying to do development and build in Deno too I don't know if Deno is fully compatibility with SvelteKit yet.
