### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by benmccann** [dbushell/sveltekit-adapter-deno#5]
You might consider listing this component on sveltesociety.dev. Or perhaps joining efforts with the other SvelteKit adapter for Deno that already exists

https://sveltesociety.dev/components#component-svelte-adapter-deno

**Comment by dbushell** [comment]
Thanks for the suggestion!

Originally this was going to be a PR to the existing adapter. I added my notes to the [related Deno Deploy issue](https://github.com/pluvial/svelte-adapter-deno/issues/40). My "fix" ended up being a complete rewrite so I published it here as a working example.

I'm hesitant to promote this adapter because ideally there would only be one (the original). But it seems like neither myself nor the original author have any time now.

I'd rather be coding SvelteKit websites but I'm stuck on WordPress projects right now 😞

**Comment by jpaquim** [comment]
@dbushell hey, I was just thinking of writing you concerning merging projects, I think it's redundant to have both and I really haven't had the time to look after svelte-adapter-deno lately, I'm not working with Deno presently. Let me know what you think, I'm happy with either upstreaming your code into my repo, or otherwise transferring the npm package name and you can rename the repo if it makes sense, whatever works for you 🙂

**Comment by dbushell** [comment]
@jpaquim I'm in a similar position I'm not doing much Svelte Kit lately. So I may not be able to maintain anything going forward!

I think it's fine though to leave both repos as they are for now. There is value in your version using Rollup which the official adapters use. Maybe someone else will come along and make a unified version.

Anyway, thanks for the comment. I'll give it more thought if I start working with Svelte Kit again.

**Comment by Malix-Labs** [comment]
_Repost from #16 (duplicate)_

## Publishing Link

https://www.sveltesociety.dev/help/submitting?type=package

## Manifest Proposal

```json
{
	"title": "sveltekit-adapter-deno",
	"repository": "https://github.com/dbushell/sveltekit-adapter-deno",
	"description": "🦕 SvelteKit Adapter for Deno and Deno Deploy",
	"npm": "sveltekit-adapter-deno",
	"categories": [
		"sveltekit-adapters"
	]
}
```

**Comment by HighPriest** [comment]
This is great!  
What about publishing it to JSR aswell?

**Comment by Malix-Labs** [comment]
Yep, would definitely be better, see #21

Also, replacing https://github.com/dbushell/sveltekit-adapter-deno/blob/d7b7cab55e3b275385ebe484b056f01075602e0a/README.md?plain=1#L13

with 

```sh
deno add npm:sveltekit-adapter-deno
```

wouldn't hurt

You know what I'm gonna PR that right away

Update: #20

**Comment by Malix-Labs** [comment]
Yep, would definitely be better

Also, replacing https://github.com/dbushell/sveltekit-adapter-deno/blob/d7b7cab55e3b275385ebe484b056f01075602e0a/README.md?plain=1#L13

with 

```sh
deno add npm:sveltekit-adapter-deno
```

wouldn't hurt

You know what I'm gonna PR that right away

**Comment by benmccann** [comment]
I think these days the official adapter-node should work?

**Comment by HighPriest** [comment]
It should, but it is not going to be comfortable for people who want to see marriage of SvelteKit & Deno 😬

**Comment by Malix-Labs** [comment]
> the official adapter-node should work?

It does, but it is a compatibility layer instead of a better rewrite

**Comment by dbushell** [comment]
Honestly I'd suggest using the official node adapter if it works. The Deno > Node compatibility layer shouldn't be a concern. From what I understand it's largely a thin layer mapping APIs.
